EXTENDED_TOPICS_V2 = {
    "Infantil": [
        {"id": "Infantil_V2_1", "title": "Developing Social Resilience in Preschoolers through Cooperative Play Models"},
        {"id": "Infantil_V2_2", "title": "The Impact of Early Musical Training on Executive Function in Toddlers"},
        {"id": "Infantil_V2_3", "title": "Neuroscience-Informed Approaches to Sensory Integration in Early Childhood"},
        {"id": "Infantil_V2_4", "title": "Digital Storytelling as a Tool for Vocabulary Development in Kindergarten"},
        {"id": "Infantil_V2_5", "title": "Evaluating the Role of Mindfulness and Self-Regulation in 3-5 Year Olds"},
        {"id": "Infantil_V2_6", "title": "The Efficacy of Nature-Based Classrooms on Motor Development in Early Years"},
        {"id": "Infantil_V2_7", "title": "Impact of Parent-Teacher Alignment on Behavioral Outcomes in Preschool"},
        {"id": "Infantil_V2_8", "title": "Cognitive Benefits of Guided Block Play in Developing Early Spatial Skills"},
        {"id": "Infantil_V2_9", "title": "Addressing Nutritional Barriers to Learning Readiness in Low-SES Preschoolers"},
        {"id": "Infantil_V2_10", "title": "The Role of Emotional Intelligence in Mitigating Separation Anxiety in Toddlers"},
        {"id": "Infantil_V3_1", "title": "Bilingualism and Working Memory: Longitudinal Evidence from Preschool Immersion"},
        {"id": "Infantil_V3_2", "title": "The Influence of Physical Environment Design on Creative Play in Early Childhood"},
        {"id": "Infantil_V3_3", "title": "Sleep Patterns and Cognitive Performance in Children Entering Primary Education"},
        {"id": "Infantil_V3_4", "title": "Assessing the Impact of Puppet-Based Pedagogy on Social-Emotional Growth"},
        {"id": "Infantil_V3_5", "title": "Early Math Literacy: Scaffolding Numerical Concepts through Gamified Tools"},
        {"id": "Infantil_V3_6", "title": "The Impact of Teacher Stress on the Classroom Climate of Early Education"},
        {"id": "Infantil_V3_7", "title": "Integrating Computational Thinking in the Early Childhood Curriculum"},
        {"id": "Infantil_V3_8", "title": "Gender Socialization in Preschool: Implications for Future Academic Choices"},
        {"id": "Infantil_V3_9", "title": "The Efficacy of Hybrid Support Models for Neurodivergent Preschoolers"},
        {"id": "Infantil_V3_10", "title": "Visual Literacy in Early Childhood: Analyzing the Role of Illustrated Media"}
    ],
    "Primaria": [
        {"id": "Primaria_V2_1", "title": "Improving Reading Comprehension through Meta-Cognitive Strategies in Grades 3-5"},
        {"id": "Primaria_V2_2", "title": "The Role of Peer-Led Inquiry in Enhancing Middle Primary Science Performance"},
        {"id": "Primaria_V2_3", "title": "Impact of 1:1 Tablet Programs on Collaborative Learning in Elementary Schools"},
        {"id": "Primaria_V2_4", "title": "Addressing Math Anxiety through Growth Mindset Interventions in Primary Ed"},
        {"id": "Primaria_V2_5", "title": "Evaluating the Efficacy of 'Brain Breaks' on Student Focus and Retention"},
        {"id": "Primaria_V2_6", "title": "The Impact of Inquiry-Based Geography Lessons on Global Awareness"},
        {"id": "Primaria_V2_7", "title": "Nutrition-Based Interventions and Academic Success: Case Studies in Primary Ed"},
        {"id": "Primaria_V2_8", "title": "The Role of Coding and Robotics in Developing Logical Reasoning in Ages 7-11"},
        {"id": "Primaria_V2_9", "title": "Teacher-Student Attachment and Its Influence on Academic Risk-Taking"},
        {"id": "Primaria_V2_10", "title": "Assessing the Impact of Flipped Learning in Primary Social Studies"},
        {"id": "Primaria_V3_1", "title": "Diversity and Inclusion: Promoting Intercultural Competency in the Classroom"},
        {"id": "Primaria_V3_2", "title": "The Long-Term Impact of Early Music Education on Primary Math Proficiency"},
        {"id": "Primaria_V3_3", "title": "Cyber-Safety Education for Elementary Students: Effective Pedagogical Models"},
        {"id": "Primaria_V3_4", "title": "Evaluating the 'Green School' Movement on Environmental Literacy in Kids"},
        {"id": "Primaria_V3_5", "title": "The Effect of Standardized Testing Pressures on Primary Teacher Autonomy"},
        {"id": "Primaria_V3_6", "title": "Integrating Mindfulness as a Preventative Measure for Bullying in Schools"},
        {"id": "Primaria_V3_7", "title": "Visual Arts Integration and the Retention of Historical Concepts in Primary Ed"},
        {"id": "Primaria_V3_8", "title": "The Impact of Flexible Seating on Student Engagement and Productivity"},
        {"id": "Primaria_V3_9", "title": "Differentiated Instruction for Gifted Learners in Mainstream Primary Settings"},
        {"id": "Primaria_V3_10", "title": "Social-Emotional Skills as Predictors of Academic Transition into Secondary Ed"}
    ],
    "Secundaria": [
        {"id": "Secundaria_V2_1", "title": "The Influence of Digital Distraction on Adolescent Deep Work and Focus"},
        {"id": "Secundaria_V2_2", "title": "Restorative Justice in Secondary Schools: Impact on Discipline and Climate"},
        {"id": "Secundaria_V2_3", "title": "Artificial Intelligence in the History Classroom: Enhancing Critical Source Analysis"},
        {"id": "Secundaria_V2_4", "title": "The Role of Peer Mentorship in Reducing High School Dropout Rates"},
        {"id": "Secundaria_V2_5", "title": "Impact of Interdisciplinary STEAM Projects on Secondary Student Motivation"},
        {"id": "Secundaria_V2_6", "title": "Evaluating the Efficacy of Career Pathing Tools in Middle School"},
        {"id": "Secundaria_V2_7", "title": "Adolescent Self-Efficacy and Performance in Online Learning Environments"},
        {"id": "Secundaria_V2_8", "title": "The Role of Ethics and Philosophy in the Modern Secondary Curriculum"},
        {"id": "Secundaria_V2_9", "title": "Addressing Sexual Health Education through Inclusive and Scientific Frameworks"},
        {"id": "Secundaria_V2_10", "title": "The Impact of School Sports Participation on Academic Self-Regulation"},
        {"id": "Secundaria_V3_1", "title": "Fostering Environmental Activism through Science Education in Teens"},
        {"id": "Secundaria_V3_2", "title": "The Psychological Effects of Academic Competition on Secondary Wellbeing"},
        {"id": "Secundaria_V3_3", "title": "Impact of Generative AI on Authorship and Integrity in High School Essays"},
        {"id": "Secundaria_V3_4", "title": "The Efficacy of Peer-Based Conflict Resolution in Urban Secondary Schools"},
        {"id": "Secundaria_V3_5", "title": "Teacher Retention in Secondary Ed: The Role of Collaborative Autonomy"},
        {"id": "Secundaria_V3_6", "title": "Digital Citizenship and the Mitigation of Social Media Echo Chambers in Youth"},
        {"id": "Secundaria_V3_7", "title": "The Role of Vocational Training in Enhancing Career Readiness for Gen Z"},
        {"id": "Secundaria_V3_8", "title": "Assessing the Impact of Gamified Science Labs on Conceptual Understanding"},
        {"id": "Secundaria_V3_9", "title": "The Influence of Family Socioeconomic Status on Secondary STEM Persistence"},
        {"id": "Secundaria_V3_10", "title": "Global Exchange Programs and the Development of Intercultural Intelligence"}
    ],
    "Bachillerato": [
        {"id": "Bachillerato_V2_1", "title": "Advanced Data Literacy: Preparing Bachillerato Students for the Quant Era"},
        {"id": "Bachillerato_V2_2", "title": "The Efficacy of Dual-Enrollment Programs on College Readiness and Success"},
        {"id": "Bachillerato_V2_3", "title": "Stress Management Workshops and Their Impact on Final Exam Performance"},
        {"id": "Bachillerato_V2_4", "title": "Developing Scientific Inquiry Skills through Independent Research in Bachillerato"},
        {"id": "Bachillerato_V2_5", "title": "The Role of Arts Education in Fostering Abstract Thinking in Senior Students"},
        {"id": "Bachillerato_V2_6", "title": "Evaluating Hybrid Models for Specialized Bachillerato in Rural Areas"},
        {"id": "Bachillerato_V2_7", "title": "The Impact of Philosophy on Critical Argumentation in Pre-University Exams"},
        {"id": "Bachillerato_V2_8", "title": "Financial Literacy in Bachillerato: Preparing Students for Economic Autonomy"},
        {"id": "Bachillerato_V2_9", "title": "Mental Health and Resilience: Targeted Interventions for the Final School Year"},
        {"id": "Bachillerato_V2_10", "title": "The Use of AI Tutoring in Advanced Calculus for High School Students"},
        {"id": "Bachillerato_V3_1", "title": "Fostering Leadership through Extracurricular Governance in Bachillerato"},
        {"id": "Bachillerato_V3_2", "title": "The Impact of Study Habits on the Transition to University Level Physics"},
        {"id": "Bachillerato_V3_3", "title": "Bilingualism in the Bachillerato: Longitudinal Impact on Cognitive Flexibility"},
        {"id": "Bachillerato_V3_4", "title": "Evaluating Performance-Based Assessment in Humanities Bachillerato"},
        {"id": "Bachillerato_V3_5", "title": "The Role of Internships in Career Goal Clarity for Pre-University Students"},
        {"id": "Bachillerato_V3_6", "title": "Addressing Information Overload in Research Tasks for Bachillerato"},
        {"id": "Bachillerato_V3_7", "title": "Cyberbullying and Social Pressure in the High-Stakes Senior Secondary Years"},
        {"id": "Bachillerato_V3_8", "title": "The Impact of Parental Pressure on Student Burnout in Bachillerato"},
        {"id": "Bachillerato_V3_9", "title": "Developing Academic Integrity through Collaborative Research Projects"},
        {"id": "Bachillerato_V3_10", "title": "The Role of Vocational Orientation in Higher Education Course Selection"}
    ],
    "Uni_Grado": [
        {"id": "UniGrado_V2_1", "title": "The Role of Project-Based Learning in Undergraduate Engineering Success"},
        {"id": "UniGrado_V2_2", "title": "Mental Health Support Systems in Higher Ed: A Review of Efficacy for Grado Students"},
        {"id": "UniGrado_V2_3", "title": "The Impact of Remote Internships on Post-Graduation Job Placement"},
        {"id": "UniGrado_V2_4", "title": "Evaluating Active Learning in Large Undergraduate Social Science Lectures"},
        {"id": "UniGrado_V2_5", "title": "Digital Literacy as a Prerequisite for Success in Contemporary Grado Programs"},
        {"id": "UniGrado_V2_6", "title": "The Crisis of Student Engagement: Re-thinking Assessment in Grado Degrees"},
        {"id": "UniGrado_V2_7", "title": "Impact of Undergraduate Research Grants on Scientific Career Intentions"},
        {"id": "UniGrado_V2_8", "title": "Social Segregation in Higher Education: Peer Effects on Undergraduate Learning"},
        {"id": "UniGrado_V2_9", "title": "The Role of Mentorship in Reducing Dropout Rates in STEM Degrees"},
        {"id": "UniGrado_V2_10", "title": "Evaluating the Efficacy of Online Collaborative Tools in Grado Capstone Projects"},
        {"id": "UniGrado_V3_1", "title": "Global Perspectives in Grado Curricula: Measuring Intercultural Competency"},
        {"id": "UniGrado_V3_2", "title": "The Impact of Part-Time Work on Undergraduate Academic Performance"},
        {"id": "UniGrado_V3_3", "title": "AI in Undergraduate Assessment: Transitioning to AI-Resistant Task Design"},
        {"id": "UniGrado_V3_4", "title": "The Role of Soft Skills Training in Law and Business Grado Degrees"},
        {"id": "UniGrado_V3_5", "title": "Peer Assessment Efficacy in Large-Scale Grado Modules"},
        {"id": "UniGrado_V3_6", "title": "The Impact of Institutional Branding on Undergraduate Career Satisfaction"},
        {"id": "UniGrado_V3_7", "title": "Developing Civic Engagement through Community-Based Undergraduate Projects"},
        {"id": "UniGrado_V3_8", "title": "The Role of Academic Libraries in Supporting Undergraduate Information Literacy"},
        {"id": "UniGrado_V3_9", "title": "Ethics in the Undergraduate Curriculum: A Comparative Analysis across Degrees"},
        {"id": "UniGrado_V3_10", "title": "Transitioning from Bachillerato to Grado: Identifying the Readiness Gap"}
    ],
    "Uni_Postgrado": [
        {"id": "UniPost_V2_1", "title": "The Economic ROI of Specialized Master's Degrees in the Global Labor Market"},
        {"id": "UniPost_V2_2", "title": "Online vs. In-Person MBA: A Comparative Analysis of Networking and Skill Gains"},
        {"id": "UniPost_V2_3", "title": "The Impact of Postgraduate Specialization on Mid-Career Promotion Rates"},
        {"id": "UniPost_V2_4", "title": "Fostering Transnational Research Collaboration in Postgraduate Cohorts"},
        {"id": "UniPost_V2_5", "title": "The Role of Industry Partnerships in the Design of Postgrado Curricula"},
        {"id": "UniPost_V2_6", "title": "Mental Health and Resilience in High-Pressure Professional Master's Programs"},
        {"id": "UniPost_V2_7", "title": "Evaluating the Efficacy of Micro-Credentials as Stackable Credits for Master's"},
        {"id": "UniPost_V2_8", "title": "Academic Integrity in the Age of AI: Challenges for Postgraduate Research"},
        {"id": "UniPost_V2_9", "title": "The Role of Executive Coaching in Postgraduate Leadership Development"},
        {"id": "UniPost_V2_10", "title": "Social Mobility and Access to Elite Postgraduate Education: A Global Review"},
        {"id": "UniPost_V3_1", "title": "The Impact of Postgraduate Mobility on Global Knowledge Transfer"},
        {"id": "UniPost_V3_2", "title": "Diversity and Representation in Postgraduate Research in Social Sciences"},
        {"id": "UniPost_V3_3", "title": "The Future of Professional Doctorate Degrees in the Corporate World"},
        {"id": "UniPost_V3_4", "title": "Evaluating Critical Thinking Gains in Interdisciplinary Master's Programs"},
        {"id": "UniPost_V3_5", "title": "The Impact of Digital Portfolio Assessment on Postgraduate Employability"},
        {"id": "UniPost_V3_6", "title": "Addressing the Skills Gap through Work-Integrated Postgraduate Learning"},
        {"id": "UniPost_V3_7", "title": "Ethics and Data Privacy in Postgraduate Data Science Training"},
        {"id": "UniPost_V3_8", "title": "The Role of Mentorship in Enhancing Retention in Master's Programs"},
        {"id": "UniPost_V3_9", "title": "Transdisciplinary Approaches to Problem Solving in Postgraduate Education"},
        {"id": "UniPost_V3_10", "title": "Transitioning from Generalist Grado to Specialist Postgrado: Cognitive Shifts"}
    ],
    "Uni_Doctorado": [
        {"id": "UniDoc_V2_1", "title": "The Impact of Remote Supervision on the Quality of Doctoral Dissertations"},
        {"id": "UniDoc_V2_2", "title": "Doctoral Attrition Rates: Identifying the Early Predictors of Withdrawal"},
        {"id": "UniDoc_V2_3", "title": "The Role of Peer Support Groups in Enhancing PhD Completion Rates"},
        {"id": "UniDoc_V2_4", "title": "Evaluating the Impact of Open Access Requirements on Doctoral Research"},
        {"id": "UniDoc_V2_5", "title": "The Mental Health Crisis in PhD Candidates: A Systematic Review of Solutions"},
        {"id": "UniDoc_V2_6", "title": "Ethics in Doctoral AI Research: Navigating Rapid Technological Change"},
        {"id": "UniDoc_V2_7", "title": "The Transition from PhD to Industry: Skills Mapping and Gap Analysis"},
        {"id": "UniDoc_V2_8", "title": "The Role of Doctoral Training Centers in Promoting Multidisciplinary Research"},
        {"id": "UniDoc_V2_9", "title": "Bibliometric Impact of Doctoral Theses: A Decade-Long Longitudinal Study"},
        {"id": "UniDoc_V2_10", "title": "The Future of the PhD Viva: Traditional Defense vs. Continuous Review"},
        {"id": "UniDoc_V3_1", "title": "Cross-Cultural Challenges in International Doctoral Supervision"},
        {"id": "UniDoc_V3_2", "title": "The Impact of Funding Structures on the Independence of Doctoral Scholars"},
        {"id": "UniDoc_V3_3", "title": "Gender Bias in Doctoral Recommendation Letters and Career Progression"},
        {"id": "UniDoc_V3_4", "title": "The Use of Big Data in Educational Doctoral Research: Ethical Frontiers"},
        {"id": "UniDoc_V3_5", "title": "Developing a Scholarly Identity during the PhD: Longitudinal Narrative Study"},
        {"id": "UniDoc_V3_6", "title": "The Role of Doctoral Education in Driving Regional Economic Innovation"},
        {"id": "UniDoc_V3_7", "title": "Addressing the 'Publication Pressure' in Modern Doctoral Programs"},
        {"id": "UniDoc_V3_8", "title": "Virtual Reality as a Methodology in Doctoral Research: Efficacy and Limits"},
        {"id": "UniDoc_V3_9", "title": "The Impact of Doctoral Mobility on Citation Metrics and Global Collaboration"},
        {"id": "UniDoc_V3_10", "title": "Doctoral Pedagogy: Preparing the Next Generation of Higher Education Faculty"}
    ],
    "Adultos": [
        {"id": "Adultos_V2_1", "title": "Digital Inclusion for the Elderly: Impact on Cognitive Health and Social Isolation"},
        {"id": "Adultos_V2_2", "title": "The Role of Adult Education in Promoting Active Citizenship and Democracy"},
        {"id": "Adultos_V2_3", "title": "Reskilling the Mid-Career Workforce: Barriers and Facilitators to Transition"},
        {"id": "Adultos_V2_4", "title": "Adult Literacy in the 21st Century: Integrating Digital and Financial Skills"},
        {"id": "Adultos_V2_5", "title": "The Psychological Impact of Lifelong Learning on Life Satisfaction in Retirement"},
        {"id": "Adultos_V2_6", "title": "Community-Based Adult Learning: Impact on Regional Social Cohesion"},
        {"id": "Adultos_V2_7", "title": "The Efficacy of Hybrid Learning for Working Adults with Family Obligations"},
        {"id": "Adultos_V2_8", "title": "Vocational Re-training in the Green Economy: Outcomes for Displaced Workers"},
        {"id": "Adultos_V2_9", "title": "The Role of Self-Directed Learning Readiness in Adult Online Education"},
        {"id": "Adultos_V2_10", "title": "Addressing the Stigma of Adult Basic Education: Strategies for Enrollment"},
        {"id": "Adultos_V3_1", "title": "Intergenerational Learning: Seniors and Youth Collaborating in Digital Space"},
        {"id": "Adultos_V3_2", "title": "The Impact of Workplace Education Programs on Corporate Innovation Rates"},
        {"id": "Adultos_V3_3", "title": "Refugee Integration through Targeted Adult Language and Civics Programs"},
        {"id": "Adultos_V3_4", "title": "Lifelong Learning for Prison Populations: Impact on Recidivism and Employment"},
        {"id": "Adultos_V3_5", "title": "The Future of Open University Models in a Post-Digital Landscape"},
        {"id": "Adultos_V3_6", "title": "Assessing Critical Thinking Gains in Non-Formal Adult Learning Settings"},
        {"id": "Adultos_V3_7", "title": "The Role of Professional Bodies in Certifying Adult Continuous Development"},
        {"id": "Adultos_V3_8", "title": "Mindfulness and Stress Reduction in Adult Community Education Programs"},
        {"id": "Adultos_V3_9", "title": "Impact of Digital Badges on the Motivation of Adult Voluntary Learners"},
        {"id": "Adultos_V3_10", "title": "Universal Basic Income and Its Potential Impact on Adult Learning Participation"}
    ],
    "Especial": [
        {"id": "Especial_V2_1", "title": "Assistive Technology for Non-Verbal Students: Impact on Social Inclusion"},
        {"id": "Especial_V2_2", "title": "Early Identification of Dyslexia: Longitudinal Impact of Tiered Interventions"},
        {"id": "Especial_V2_3", "title": "The Role of Sensory Environments in Reducing Anxiety in Students with Autism"},
        {"id": "Especial_V2_4", "title": "Teacher Competency in IEP Development: A Comparative International Study"},
        {"id": "Especial_V2_5", "title": "Social Skills Training via Virtual Reality for Neurodivergent Adolescents"},
        {"id": "Especial_V2_6", "title": "Addressing the Double Stigma: Inclusion of Minority Groups in Special Ed"},
        {"id": "Especial_V2_7", "title": "The Efficacy of Co-Teaching Models in Inclusive Secondary Classrooms"},
        {"id": "Especial_V2_8", "title": "Transitions to Adulthood: Support Systems for Special Needs Students in HE"},
        {"id": "Especial_V2_9", "title": "The Impact of Parental Advocacy on Resource Allocation in Special Education"},
        {"id": "Especial_V2_10", "title": "Evaluating the Role of Paraprofessionals in Inclusive Primary Education"},
        {"id": "Especial_V3_1", "title": "Universal Design for Learning (UDL) in Science Labs: Best Practices for Special Ed"},
        {"id": "Especial_V3_2", "title": "The Neurodiversity Paradigm in Schools: Moving beyond the Medical Model"},
        {"id": "Especial_V3_3", "title": "Impact of Early Speech Therapy on Long-Term Academic Outcomes"},
        {"id": "Especial_V3_4", "title": "Behavioral Interventions for ADHD: A Meta-Analysis of School-Based Programs"},
        {"id": "Especial_V3_5", "title": "Ethics of Wearable Tech in Monitoring Behavioral Triggers in Special Ed"},
        {"id": "Especial_V3_6", "title": "Promoting Self-Determination in Students with Intellectual Disabilities"},
        {"id": "Especial_V3_7", "title": "The Role of Art Therapy in Supporting Emotional Regulation in Special Needs"},
        {"id": "Especial_V3_8", "title": "Global Trends in Special Education Funding: Equity vs. Efficiency"},
        {"id": "Especial_V3_9", "title": "The Impact of Inclusive Physical Education on Social Belongingness"},
        {"id": "Especial_V3_10", "title": "Predictors of Teacher Burnout in High-Support Special Education Settings"}
    ]
}
