TOPICS = [
    # ... (First 10 already defined)
    {"id": "EvidenceInnovation", "title": "Evidence-Based Education vs. Pedagogical Innovation: Bridging the Gap in Contemporary Pedagogy"},
    {"id": "GenAI_Assessment", "title": "Generative Artificial Intelligence in Academic Assessment: Navigating the Integrity-Innovation Dilemma"},
    {"id": "StandardizedFormative", "title": "Re-evaluating Standardized Testing: A Comparative Analysis of Formative Assessment Efficacy"},
    {"id": "HybridLearning", "title": "The Post-Pandemic Hybrid Learning Paradigm: Empirical Evidence of Student Engagement and Outcomes"},
    {"id": "NeuroeducationMitos", "title": "Critical Review of Neuroeducation: Identifying and Addressing Neuromyths in Teacher Training"},
    {"id": "InclusionSpecialized", "title": "Inclusive Education for Neurodivergent Learners: Evaluating the Efficacy of Specialized vs. Mainstream Settings"},
    {"id": "GamificationImpact", "title": "The Real Impact of Gamification on Cognitive Retention: A Systematic Review of Empirical Studies"},
    {"id": "CompetencyTraditional", "title": "Competency-Based vs. Content-Centric Education: Realigning Curriculum for the 21st Century Labor Market"},
    {"id": "SocialEmotional", "title": "The Scientific Basis of Social-Emotional Learning: Impact on Academic Performance and Wellbeing"},
    {"id": "DigitalDivideAI", "title": "Addressing the Digital Divide: Socioeconomic Barriers to AI Literacy and Educational Equity"},

    # New 90 topics
    {"id": "DigitalCitizenship", "title": "Cultivating Digital Citizenship: Ethical Frameworks for Student Interaction in Social Media"},
    {"id": "OER_Sustainability", "title": "The Economic and Pedagogical Sustainability of Open Educational Resources (OER) in Higher Education"},
    {"id": "TeacherBurnout", "title": "Systemic Drivers of Teacher Burnout: A Meta-Analysis of Workload and Mental Health Interventions"},
    {"id": "HomeschoolingDigital", "title": "The Evolution of Homeschooling: Impact of Digital Platforms on Student Achievement and Socialization"},
    {"id": "MontessoriDigital", "title": "Integrating Montessori Principles in the Digital Age: Balancing Screen Time with Sensory Learning"},
    {"id": "STEAM_Integration", "title": "From STEM to STEAM: Evaluating the Impact of Arts Integration on Scientific Innovation"},
    {"id": "CriticalThinkingFakeNews", "title": "Developing Critical Thinking in the Era of Post-Truth: Media Literacy in the K-12 Curriculum"},
    {"id": "PeerAssessment", "title": "The Efficacy of Peer Assessment in Undergraduate Education: Reliability and Student Perception"},
    {"id": "FlippedClassroomLongitudinal", "title": "Longitudinal Effects of the Flipped Classroom Model on Knowledge Retention in STEM"},
    {"id": "PBL_AuthenticLearning", "title": "Project-Based Learning and Authentic Assessment: Preparing Students for Real-World Problem Solving"},
    {"id": "RuralEducationAccess", "title": "Overcoming Geographic Barriers: The Role of Satellite Internet in Rural Educational Equity"},
    {"id": "SustainableDevelopmentEdu", "title": "Education for Sustainable Development: Integrating the SDGs into National Curricula"},
    {"id": "VocationalTrends", "title": "The Future of Vocational Training: Apprenticeships in the High-Tech Gig Economy"},
    {"id": "LanguageLearningAI", "title": "Artificial Intelligence in Second Language Acquisition: Personalized Feedback vs. Human Interaction"},
    {"id": "DyslexiaDigitalTools", "title": "Assistive Technologies for Dyslexic Learners: Impact on Reading Fluency and Self-Esteem"},
    {"id": "ExecutiveFunctionEarly", "title": "Scaffolding Executive Function in Early Childhood: Longitudinal Impact on Academic Success"},
    {"id": "SchoolLeadershipModels", "title": "Distributed Leadership in Schools: Impact on Teacher Retention and Student Climate"},
    {"id": "HigherEdFinancing", "title": "The Crisis of Higher Education Financing: Exploring Income-Share Agreements as an Alternative"},
    {"id": "StudentLoanPedagogy", "title": "The Psychological Impact of Student Debt on Academic Choices and Career Pathing"},
    {"id": "LifelongLearningGig", "title": "Lifelong Learning in the Gig Economy: The Role of Micro-Credentials in Workforce Agility"},
    {"id": "MicroCredentialsDegrees", "title": "Micro-Credentials vs. Traditional Degrees: A Comparative Analysis of Employer Perception"},
    {"id": "VR_MedicalEdu", "title": "Virtual Reality in Medical Education: Enhancing Surgical Precision through Immersive Simulation"},
    {"id": "AR_HistoryClass", "title": "Augmented Reality in the History Classroom: Visualizing the Past for Enhanced Engagement"},
    {"id": "PlayPrimaryEdu", "title": "The Neurobiology of Play: Why Guided Play is Essential for Primary Science Education"},
    {"id": "ClassroomDesignLearning", "title": "Flexible Learning Spaces: How Classroom Architecture Affects Student Collaboration"},
    {"id": "SchoolSafetyTech", "title": "The Ethics of Surveillance in Schools: Balancing Safety with Student Privacy Rights"},
    {"id": "StudentDataPrivacy", "title": "Big Data in Education: Navigating the Ethical Risks of Predictive Analytics"},
    {"id": "GenderGapSTEM", "title": "Addressing the Gender Gap in STEM: Early Interventions and Mentorship Efficacy"},
    {"id": "MentalHealthSchools", "title": "Scaling Mental Health Support in K-12: The Role of Tele-Counseling and SEL"},
    {"id": "SocialMediaAttention", "title": "Short-Form Video and Student Attention Span: Implications for Instructional Design"},
    {"id": "BilingualismCognitive", "title": "Bilingualism and Cognitive Flexibility: Longitudinal Evidence from Dual-Language Immersion"},
    {"id": "SpecialEduFunding", "title": "The Economics of Special Education: Evaluating the Long-Term ROI of Early Intervention"},
    {"id": "SmartClassrooms", "title": "The Efficacy of 'Smart' Classrooms: Do Interactive Whiteboards Improve Learning Outcomes?"},
    {"id": "FutureTextbooks", "title": "The Death of the Textbook: Transitioning to Dynamic, Open-Access Digital Curricula"},
    {"id": "OpenScienceResearch", "title": "Open Science in Educational Research: Challenges of Data Sharing and Transparency"},
    {"id": "AcademicFreedom21C", "title": "Academic Freedom in the 21st Century: Navigating Political Polarization on Campus"},
    {"id": "UniversityRankings", "title": "The Impact of Global University Rankings on Institutional Strategy and Research Quality"},
    {"id": "TeacherSalaryPerformance", "title": "Teacher Compensation and Student Achievement: A Cross-National Comparative Study"},
    {"id": "ParentalInvolvementDigital", "title": "Parental Involvement in Digital Learning: Barriers and Facilitators in Low-SES Households"},
    {"id": "SchoolChoiceEquity", "title": "School Choice and Socioeconomic Segregation: A Meta-Analysis of Charter School Impact"},
    {"id": "GamificationMath", "title": "Gamifying Mathematics: Impact on Anxiety and Performance in Middle School"},
    {"id": "CodingK12", "title": "Is Coding the New Literacy? Integrating Computer Science into the Primary Curriculum"},
    {"id": "EthicsAI_Edu", "title": "Ethics of AI in Education: Bias, Accountability, and the Human-in-the-Loop Principle"},
    {"id": "SoftSkillsMeasurement", "title": "Measuring the Unmeasurable: New Frameworks for Assessing Soft Skills in Higher Ed"},
    {"id": "AdultLiteracyTech", "title": "Digital Tools for Adult Literacy: Overcoming the Stigma and Enhancing Employment"},
    {"id": "GlobalSouthTech", "title": "EdTech in the Global South: Low-Bandwidth Solutions for Educational Resilience"},
    {"id": "NeurodiversityEmployment", "title": "From Classroom to Workplace: Supporting Neurodivergent Transitions through CBE"},
    {"id": "ClimateChangeCurriculum", "title": "Climate Change in the Curriculum: Moving from Awareness to Action-Oriented Pedagogy"},
    {"id": "EthicsLearningAnalytics", "title": "The Ethics of Learning Analytics: Transparency and Student Consent in Data Usage"},
    {"id": "TeacherAgencyInnovation", "title": "Teacher Agency as a Driver of Innovation: Decoupling Pedagogy from Policy Constraints"},
    {"id": "StudentEngagementMetrics", "title": "Beyond Attendance: Real-Time Metrics for Measuring Cognitive Student Engagement"},
    {"id": "HigherEdAccessibility", "title": "Universal Design for Learning in Higher Education: Beyond Compliance to Inclusion"},
    {"id": "IndigenousKnowledgeEdu", "title": "Integrating Indigenous Knowledge Systems into Science Education: A Post-Colonial Review"},
    {"id": "RemoteExamProctoring", "title": "The Controversy of Remote Proctoring: Surveillance, Privacy, and Test Anxiety"},
    {"id": "AdaptiveLearningEfficacy", "title": "The Efficacy of Adaptive Learning Systems in Large-Scale Introductory Courses"},
    {"id": "TeacherIdentityProfessional", "title": "Developing Teacher Identity in the Age of Accountability: Professionalism vs. Compliance"},
    {"id": "SchoolGovernanceModels", "title": "Democratic School Governance: Impact on Student Civic Engagement and Responsibility"},
    {"id": "MindfulnessInSchools", "title": "Mindfulness in the Classroom: Evidence of Impact on Executive Function and Stress"},
    {"id": "ArtsEducationCognition", "title": "The Cognitive Benefits of Music Education: A Meta-Analysis of Executive Function"},
    {"id": "LibraryFutureResearch", "title": "The Future of the Academic Library: From Book Repository to Research Hub"},
    {"id": "DoctoralSupervision", "title": "Evolving Models of Doctoral Supervision: From Apprenticeship to Mentorship Circles"},
    {"id": "CommunityCollegesTech", "title": "Community Colleges and the Tech Workforce: Re-skilling for the AI Revolution"},
    {"id": "GlobalCitizenshipEdu", "title": "Education for Global Citizenship: Navigating Identity in an Age of Nationalism"},
    {"id": "PhysicalEduBrain", "title": "Exercise and the Brain: The Impact of Physical Education on Cognitive Performance"},
    {"id": "CyberbullyingPrevention", "title": "Evidence-Based Cyberbullying Prevention: The Role of Peer Mediation and SEL"},
    {"id": "StudentVoicePolicy", "title": "The Impact of Student Voice on School Policy: Case Studies of Democratic Reform"},
    {"id": "TeacherResearchLiteracy", "title": "Enhancing Teacher Research Literacy: Bridging the Practitioner-Researcher Divide"},
    {"id": "OnlineCollaborationTools", "title": "The Efficacy of Online Collaboration Tools in Enhancing Group Work Performance"},
    {"id": "HigherEdInternationalization", "title": "The Impact of Internationalization on Higher Education: Diversity vs. Commercialization"},
    {"id": "PreschoolEquity", "title": "Universal Preschool and the Achievement Gap: Longitudinal Evidence from Global Models"},
    {"id": "TeacherRecruitmentCrisis", "title": "Solving the Teacher Recruitment Crisis: Incentives, Working Conditions, and Status"},
    {"id": "EducationalPhilanthropy", "title": "The Role of Philanthropy in Education: Innovation Driver or Policy Disruptor?"},
    {"id": "DigitalNoteTaking", "title": "Digital vs. Handwritten Note-Taking: Impact on Conceptual Understanding and Recall"},
    {"id": "AI_TutoringSystems", "title": "Intelligent Tutoring Systems: Can AI Replace One-on-One Human Tutoring?"},
    {"id": "SchoolLunchCognition", "title": "Nutrition and Cognition: The Impact of School Lunch Programs on Academic Performance"},
    {"id": "TeacherTrainingInclusion", "title": "Preparing Teachers for Diversity: A Review of Inclusive Pedagogy in Initial Training"},
    {"id": "HigherEdRetention", "title": "Predictive Modeling for Student Retention: Ethical Use of At-Risk Data"},
    {"id": "GamificationLanguage", "title": "Gamified Language Learning: Longitudinal Impact on Vocabulary Acquisition"},
    {"id": "StudentAgencyChoice", "title": "Student Agency and Course Choice: Impact on Motivation and Career Preparedness"},
    {"id": "HigherEdMentalHealth", "title": "The Student Mental Health Crisis in Higher Ed: Institutional Responsibility and Action"},
    {"id": "OpenPedagogyStudents", "title": "Students as Creators: The Role of Open Pedagogy in Enhancing Academic Engagement"},
    {"id": "EthicsEducationalMarketing", "title": "The Ethics of Educational Marketing: Navigating Student Recruitment in a Competitive Market"},
    {"id": "VR_SocialSkills", "title": "Virtual Reality for Social Skills Training in Autism: A Systematic Review"},
    {"id": "TeacherCollaborationDigital", "title": "Professional Learning Networks (PLNs): Impact of Digital Collaboration on Teacher Growth"},
    {"id": "SchoolAutonomyPerformance", "title": "School Autonomy and Performance: A Global Comparative Analysis of PISA Data"},
    {"id": "DigitalLiteracyAdults", "title": "Promoting Digital Literacy for Seniors: Bridging the Intergenerational Tech Gap"},
    {"id": "HigherEdWorkIntegrated", "title": "Work-Integrated Learning (WIL): Impact on Graduate Employability and Skills Gap"},
    {"id": "EthicsCrowdsourcedResearch", "title": "The Ethics of Crowdsourced Research in Education: Data Quality and Participant Rights"},
    {"id": "SchoolEnvironmentWellbeing", "title": "The Impact of School Environment on Student Wellbeing: Light, Noise, and Air Quality"},
    {"id": "FutureOfTeachingAI", "title": "The Future of the Teaching Profession: Co-existing with AI and Automation"}
]
